[package]
name = "router-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
router-core = { path = "../router-core" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]
